//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iwanttobuy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IwanttobuyCustomer
    {
        public int CustomerPK { get; set; }
        [Required]
        public string CustomerName { get; set; }
        [Required]
        public string CustomerSurname { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string TextPassword { get; set; }
        public byte[] Password { get; set; }
        public string CustomerType { get; set; }
        [Required]
        public string PhoneNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int NoOfLogin { get; set; }
        public string Address { get; set; }
    }
}
